### ISSUE TITLE
Discard window

### ISSUE THREAD

**Issue by ScottVaughan** [thyer/CS340winter2016#326] opened 2016-03-03 04:16 UTC
Discard window does not disappear when clicking the discard button.

**Comment by dbitter2** [comment] 2016-03-06 23:26
invalid? what's the discard button?

**Comment by Sicilica** [comment] 2016-03-07 05:32
@dbitter2 Should be the button that says eg "2/2" for cards to discard.

This was most likely a duplicate of issue #436

**Closed** 2016-03-07 21:40 UTC
Labels: P3: Incorrect behavior that affects gameplay, Phase 2, Team 12
