### ISSUE TITLE
Cannot register a user

### ISSUE THREAD

**Issue by cbhomestar** [thyer/CS340winter2016#171] opened 2016-03-02 23:04 UTC
I get a server error whenever I try to register.

<img width="1440" alt="screen shot 2016-03-02 at 3 58 14 pm" src="https://cloud.githubusercontent.com/assets/9063768/13478857/4fef5946-e090-11e5-958b-4f402ebd0f8f.png">

**Comment by KasiKarra** [comment] 2016-03-04 01:39
What kind of users were you trying to register as?

**Comment by cbhomestar** [comment] 2016-03-04 23:10
I tried Brandon for the username and brandon for the password and I got an error.

**Comment by thyer** [comment] 2016-03-14 18:02
Plausibly caused by something else, but I couldn't duplicate. Closing as invalid.

**Closed by thyer** 2016-03-14 18:02 UTC
Labels: invalid, Phase 2, Team 6
