### ISSUE TITLE
Inaccurate number of cities in resource bar 

### ISSUE THREAD

**Issue by emeraldarcher** [thyer/CS340winter2016#197] opened 2016-03-02 23:34 UTC
Building a city doesn't decrease the number of cities the player has.

**Comment by thyer** [comment] 2016-03-04 23:26
@mountain01 Mind tagging the duplicate issue?

**Comment by mountain01** [comment] 2016-03-04 23:49
@thyer This issue is linked with #100. As I read the description for it, I guess I split it into two parts and this is a duplicate of the second part, only with cities instead of settlements. The functionality is so closely related that I marked this as a duplicate. If you fee like that shouldn't be the case then we can un mark this one.

**Comment by thyer** [comment] 2016-03-08 00:37
Closing this as duplicate

**Closed by thyer** 2016-03-08 00:37 UTC
Labels: duplicate, fixed, Phase 2, Team 3
