### ISSUE TITLE
Player placing roads for another player

### ISSUE THREAD

**Issue by ScottVaughan** [thyer/CS340winter2016#363] opened 2016-03-03 05:08 UTC
Related to an earlier related issue (issue #321), after restarting the client to jump start things, The game goes crazy. 

Initial set-up stage: Sam’s turn. Brooke somehow is asked to place a road, and upon placing it, it places a road for Mark, forbids Brooke from playing a settlement. Restarting Marks client does not let him do anything, meanwhile restarting Brooke’s client has given her the ability to play every single road without consequence, granted the roads Brooke plays, are Marks…. I suspect something in the client has gone awry in the way it creates instances and checks to see who can play what, when, and where.

**Comment by dbitter2** [comment] 2016-03-06 23:57
fixed

**Comment by Sicilica** [comment] 2016-03-07 05:31
Duplicate of issue #436

**Closed** 2016-03-07 21:41 UTC
Labels: duplicate, fixed, P2: Blocking gameplay, Phase 2, Team 12
