### ISSUE TITLE
Largest Army not showing up (Jacob)

### ISSUE THREAD

**Issue by jtmingus** [thyer/CS340winter2016#218] opened 2016-03-03 00:48 UTC
You have to close out of and rejoin a game for the largest army icon to show up.

**Comment by jakebrucebrewer** [comment] 2016-03-08 06:38
@thyer Hey Trent. we decided that this one was a duplicate of #292. I just wanted to confirm that this one is closed and isn't affecting our score adversely. Thanks.

**Comment by thyer** [comment] 2016-03-09 18:27
Closing as duplicate

**Closed by thyer** 2016-03-09 18:27 UTC
Labels: duplicate, fixed, P4: Incorrect behavior that doesn't affect gameplay, Phase 2, Team 1
