### ISSUE TITLE
Maritime Trade

### ISSUE THREAD

**Issue by misterpink14** [thyer/CS340winter2016#211] opened 2016-03-03 00:32 UTC
The Maritime Trade button is enabled in Setup phase. It should be disabled.

<img width="542" alt="screen shot 2016-03-02 at 5 27 20 pm" src="https://cloud.githubusercontent.com/assets/9299960/13480665/a1c0c2da-e09c-11e5-9126-7cc96b29afe9.png">

**Comment by thyer** [comment] 2016-03-07 19:10
Marking as dupe of button activation

**Closed** 2016-03-08 00:17 UTC
Labels: duplicate, fixed, P4: Incorrect behavior that doesn't affect gameplay, Phase 2, Team 6
