### ISSUE TITLE
Rolling rolls two number sometimes 3 and allocate resources for all rolls

### ISSUE THREAD

**Issue by jpp46** [thyer/CS340winter2016#309] opened 2016-03-03 03:56 UTC
<img width="343" alt="screen shot 2016-03-02 at 8 53 44 pm" src="https://cloud.githubusercontent.com/assets/11218420/13484229/29321a54-e0b9-11e5-9a2b-aeea43f529f6.png">
@team2

**Comment by emeraldarcher** [comment] 2016-03-04 23:19
@jpp46 Can you provide me with detailed steps to reproduce this bug?

**Comment by thyer** [comment] 2016-03-07 22:44
Closing because no steps were given for reproduction

**Closed by thyer** 2016-03-07 22:44 UTC
Labels: Phase 2, Team 2
