### ISSUE TITLE
Team 19 - rejoining a game after winning

### ISSUE THREAD

**Issue by rysav** [thyer/CS340winter2016#144] opened 2016-03-02 20:11 UTC
After you win a game it properly allows me to join/create a new game, but when I join all the settlements/roads/ports are drawn on the map still. I can build stuff on top of them so they arent in the model, but they are on the view.

**Comment by jmbarzee** [comment] 2016-03-07 00:53
It looks like a lot of teams solved this by just closing the client. I vote we do the same

**Comment by joshuahaertel** [comment] 2016-03-07 12:33
The problem is that that is not what the spec says to do, furthermore, they can still re-join the game.

**Closed** 2016-03-30 16:54 UTC
Labels: invalid, P3: Incorrect behavior that affects gameplay, Phase 2, Team 19
