### ISSUE TITLE
placing a settlement after a road

### ISSUE THREAD

**Issue by ScottVaughan** [thyer/CS340winter2016#307] opened 2016-03-03 03:54 UTC
Unable to place a settlement after first road is “placed.”  Even after restarting the client, this issue persisted. This is during the players initial turns around the board.

**Comment by dbitter2** [comment] 2016-03-06 23:27
fixed

**Comment by Sicilica** [comment] 2016-03-07 05:29
Duplicate of issue #436

**Closed** 2016-03-07 21:41 UTC
Labels: duplicate, fixed, P3: Incorrect behavior that affects gameplay, Phase 2, Team 12
