### ISSUE TITLE
Team 2 - Can't add AIs

### ISSUE THREAD

**Issue by jakebrucebrewer** [thyer/CS340winter2016#248] opened 2016-03-03 02:51 UTC
Team 2 Bug: 
Whenever you try to add AIs it just quits out of the menu and doesn't add an AI.

**Comment by emeraldarcher** [comment] 2016-03-04 02:49
Phase 2 spec doesn't require AI players.

**Comment by jakebrucebrewer** [comment] 2016-03-04 19:06
Gotcha. Cool.

**Comment by thyer** [comment] 2016-03-07 18:14
@emeraldarcher Could you guys conceivably disable the AddAI button? I do have to mark this as a valid issue since you've left in a button that breaks stuff.

**Comment by thyer** [comment] 2016-03-07 22:51
Duplicate of #299

**Closed by thyer** 2016-03-07 22:51 UTC
Labels: duplicate, P3: Incorrect behavior that affects gameplay, Phase 2, Team 2
