### ISSUE TITLE
Double Discard

### ISSUE THREAD

**Issue by byurfl** [thyer/CS340winter2016#356] opened 2016-03-03 04:46 UTC
If a 7 is rolled and a player has more than 14 resource cards, they are forced to discard twice.

Steps to reproduce:
1. Get more than 14 resource cards in your hand (e.g. 20).
2. Roll a 7.
3. Discard 10 cards when the discarding modal appears.
4. The modal appears again, forcing you to discard another 5 cards.

**Comment by thyer** [comment] 2016-03-04 22:31
@jakebrucebrewer I didn't immediately see which issue this was a duplicate of, would you mind commenting which number that is?

**Comment by thyer** [comment] 2016-03-10 16:47
Verified -- fixed

**Closed** 2016-03-30 16:50 UTC
Labels: fixed, P3: Incorrect behavior that affects gameplay, Phase 2, TA-Fixed, Team 1
