### ISSUE TITLE
D-Trade doesn't give the initiator of the trade anything, and he doesn't lose anything

### ISSUE THREAD

**Issue by CaptBoscho** [thyer/CS340winter2016#57] opened 2016-03-01 23:29 UTC

**Comment by DanielSaunders** [comment] 2016-03-02 04:24
This seems to be a duplicate of https://github.com/thyer/CS340winter2016/issues/55 and does not seem to happen anymore.

**Comment by thyer** [comment] 2016-03-02 18:44
Please don't close issues you didn't open

**Closed** 2016-03-10 17:08 UTC
Labels: duplicate, fixed, P3: Incorrect behavior that affects gameplay, Phase 2, Team 3
