### ISSUE TITLE
Phase 2 Team 2 Blank Username Password

### ISSUE THREAD

**Issue by jvansteeter** [thyer/CS340winter2016#252] opened 2016-03-03 03:13 UTC
Not entirely sure if this is a bug or not, so I figured I'd post it and let the TAs decide.  
When registering, a blank username is an acceptable username that can get registered.  As well is a blank password considered a valid password.  Technically may not be a bug, but that's not a good thing for a system to have.

**Comment by emeraldarcher** [comment] 2016-03-04 02:57
Duplicate with #286. Not a bug, as mentioned, under Phase 2 spec.

**Comment by thyer** [comment] 2016-03-07 22:50
Closing as duplicate

**Closed by thyer** 2016-03-07 22:50 UTC
Labels: duplicate, fixed, Phase 2, Team 2
