### ISSUE TITLE
Domestic Trade enabled on setup round

### ISSUE THREAD

**Issue by misterpink14** [thyer/CS340winter2016#210] opened 2016-03-03 00:29 UTC
When you join a new game, the Domestic Trade button is enabled. It should be disabled during startup phases.
<img width="1350" alt="screen shot 2016-03-02 at 5 26 10 pm" src="https://cloud.githubusercontent.com/assets/9299960/13480637/4a4b7bd0-e09c-11e5-8ab0-8faed187b8a0.png">

**Comment by thyer** [comment] 2016-03-07 16:48
marking as duplicate of #211

**Closed** 2016-03-07 18:39 UTC
Labels: duplicate, fixed, Phase 2, Team 6
