### ISSUE TITLE
Longest Road Issues

### ISSUE THREAD

**Issue by KasiKarra** [thyer/CS340winter2016#382] opened 2016-03-03 06:22 UTC
If you implemented the Longest Road algorithm you forgot to mention it to us so that we couldn't log bugs against you.   The "most roads" don't always work, and sometimes transfers to other people.

**Comment by byurfl** [comment] 2016-03-03 15:10
The longest road algorithm wasn't part of this phase - that happens server-side. We just take the player index from the model and assign the points to that player. Are you saying that this isn't working correctly? Could you give us some steps to reproduce the error?

**Comment by KasiKarra** [comment] 2016-03-03 17:02
That's what I thought, but it was the only explanation that we could come up with.  I don't have the program with me at the moment, but I will try to reproduce it this afternoon.  Here are a few screen shots that I saved from the game    (hopefully they upload correctly)
On the top left Quinn has 6 roads, but no points for the longest road and on the bottom right Rebecca stole the longest road even though Quinn has more roads

![catan](https://cloud.githubusercontent.com/assets/16614325/13502144/fb82ca36-e126-11e5-8ac7-da8186a1b2a7.png)

**Comment by byurfl** [comment] 2016-03-04 04:02
I think I remember Dr. Rodham mentioning extra credit for implementing the "real" longest road algorithm server-side. Maybe the demo server uses that one. In any case, some more specific steps to reproduce the error would be really helpful.

**Comment by KasiKarra** [comment] 2016-03-04 19:43
Currently unable to reproduce that specific example.  I played all 4 players.  Top screen shot Sam has 6 roads in play so should have the longest road.  3 turns later I am finally able to build another road and am finally awarded the longest road.  Longest road goes to whoever have more than 5 roads.

![settlers road](https://cloud.githubusercontent.com/assets/16614325/13538216/7d236db8-e206-11e5-8427-178a7702fd84.png)

**Comment by KasiKarra** [comment] 2016-03-04 19:50
Got it.  Sam has 11 roads, and Pete has 9, but Longest(most) roads still goes to Sam  (I took the previous game and just kept adding roads in a line until this came)
![settlers road21](https://cloud.githubusercontent.com/assets/16614325/13538406/953802b4-e207-11e5-8b99-ee8b5a6564a4.png)

**Comment by byurfl** [comment] 2016-03-04 19:57
I would argue that this is correct behavior. From the functional spec:

"**Longest road is awarded to the first player to build a road five segments long;** largest army is given to the first player to play three soldier cards. Each award is passed on as players build **longer roads** and larger armies."

So even though Sam has more roads overall, his longest road is only 5 segments long. Pete's longest road is 9 segments long, so Pete gets the award.

@thyer, can you confirm that this is expected behavior from the demo server?

**Comment by jjwilbur** [comment] 2016-03-04 21:05
Yeah longest road isn't who has the most roads placed on the board. It is based on if you have the most roads connected in a line.  Also that line can't branch out and come back to continue counting.  For example for Sam the top portion he only has a max of 5 because of branching.  Pete has the longest road because his is one long connected road.  Thus Pete should have the longest road.... and does.

**Comment by thyer** [comment] 2016-03-04 22:19
@byurfl and @jjwilbur Ryan is correct - the server is the one who assigns longest road, and server does longest road, not most roads. Next phase, you'll implement the server and will have the option of whether you do longest road or not. Closing this issue as invalid.

**Closed by thyer** 2016-03-04 22:19 UTC
Labels: invalid, Phase 2, Team 7
