### ISSUE TITLE
Robbing error

### ISSUE THREAD

**Issue by airhop** [thyer/CS340winter2016#349] opened 2016-03-03 04:39 UTC
Sometimes after moving a robber, not allowing you to finish your turn unless you close the screen and log back in

**Comment by kking937** [comment] 2016-03-03 15:20
Trying to reproduce this error, and I cannot do it.  Can you please go in more detail telling how you were able to get this to happen?

**Comment by thyer** [comment] 2016-03-08 01:06
Will attempt to dupe during TA testing

**Comment by thyer** [comment] 2016-03-14 18:21
Closing as invalid. Couldn't dupe during testing

**Closed by thyer** 2016-03-14 18:21 UTC
Labels: invalid, P3: Incorrect behavior that affects gameplay, Phase 2, Team 7
