### ISSUE TITLE
Players turn

### ISSUE THREAD

**Issue by ScottVaughan** [thyer/CS340winter2016#336] opened 2016-03-03 04:26 UTC
When ending your turn, if the next player is playing on another computer, the “Finish Turn” option doesn’t go away, the other player can roll the dice, but they cannot do anything other than that. Meanwhile, the “Finish Turn” option does not go away from the original player, who can then click it at will to skip everyone else’s turn, allow you to go again. Everything seems to cascade out of control after that. Half the players can’t view their victory points, it stops tracking who’s turn it is, and the game does not allow any moves or actions to be taken.

**Comment by dbitter2** [comment] 2016-03-06 23:25
fixed

**Comment by Sicilica** [comment] 2016-03-07 05:36
Other players being unable to act was a duplicate of issue #436 

The "Finish Turn" option not disappearing was a valid bug, though probably P4 unless some player chooses to troll his opponents.

The "stops tracking who's [sic] turn it is and the game does not allow any moves or actions to be taken" is probably a result of a 7 roll forcing one of the players who couldn't act as per #436 to move the robber, or some other state that could not be fixed. With a vague description, it's only clear that some unresolvable condition was reached, but it certainly can't be reproduced.

**Closed** 2016-03-07 21:40 UTC
Labels: fixed, P2: Blocking gameplay, Phase 2, Team 12
