### ISSUE TITLE
5 Player allowed to join a game

### ISSUE THREAD

**Issue by kking937** [thyer/CS340winter2016#566] opened 2016-03-25 22:57 UTC
A 5th player is able to join a game that has already been started.

1. Login and have a player create a game
2. Have 4 other players login on separate clients
3. Have 3 of the players join the game so it starts
4 Have the 5th player join the game.

**Comment by thyer** [comment] 2016-03-28 17:03
@yeyyosing Joel I'm not seeing which one this is a duplicate of, can you tag it?

**Comment by CaptBoscho** [comment] 2016-03-28 22:21
It's a duplicate of #546

**Comment by derekargueta** [comment] 2016-03-29 09:15
Confirmed duplicate. #546 describes this exact problem of being able to join a full game. @thyer can this issue be closed?

**Comment by thyer** [comment] 2016-03-30 00:44
Closing now

**Closed by thyer** 2016-03-30 00:44 UTC
Labels: duplicate, Phase 3, Team 2
