### ISSUE TITLE
robbing client doesn't update

### ISSUE THREAD

**Issue by dannyharding10** [thyer/CS340winter2016#650] opened 2016-03-26 04:45 UTC
when a 7 is rolled the person who rolled has to wait for others to discard.  after everyone else discards, the client of the person who rolled 7 is stuck at "wait for other players to discard".  You have to close and restart for it to allow you to continue.

**Comment by eaglewyng** [comment] 2016-03-26 05:15
This is a duplicate of a bug that was already filed.

**Closed** 2016-03-31 21:35 UTC
Labels: duplicate, Phase 3, Team 4
