### ISSUE TITLE
Trade Ports

### ISSUE THREAD

**Issue by ztnelson01** [thyer/CS340winter2016#119] opened 2016-03-02 19:32 UTC
For Maritime trade it looks like some of the 2:1 ports are working (brick port worked but wood port didn't). 3:1 ports aren't working. I can't trade when I should be able to because of this problem.

**Comment by hunterrees** [comment] 2016-03-02 19:41
![thumb_img_0540_1024](https://cloud.githubusercontent.com/assets/16613772/13472895/2102dda4-e074-11e5-87df-01ecf002243d.jpg)
We are red in this case

**Comment by panzertime** [comment] 2016-03-04 17:52
Seems like ore works fine.  Could take a while to check all of these.

**Comment by ztnelson01** [comment] 2016-03-04 18:05
Yeah, sorry I wasn't more thorough in testing all of the maritime trade
resources. It could have something to do with another factor at play, but
sometimes maritime trade wasn't being allowed even though I was on a port.
I'm not sure why some ports would work while others don't. Sorry >_<

**Comment by panzertime** [comment] 2016-03-04 18:27
Sheep's fine too.

(I'm making these comments as notes to myself, you don't need to worry about them)

**Comment by panzertime** [comment] 2016-03-04 18:30
So I managed to get a 3:1 to work with bricks

**Comment by panzertime** [comment] 2016-03-04 18:45
This appears to be fixed

**Comment by thyer** [comment] 2016-03-04 22:29
@panzertime was this bug ever reproducible? Also, if you can figure out that it was related to another issue, if you would mark that here? That allows for a bit more mercy since this is marked as a P3 and we'd hate to take off more points than we need to.

**Comment by panzertime** [comment] 2016-03-07 08:13
It was reproduced, I was using the wrong client.

**Comment by panzertime** [comment] 2016-03-07 09:40
This is fixed now

**Closed** 2016-03-30 16:54 UTC
Labels: fixed, P3: Incorrect behavior that affects gameplay, Phase 2, Team 19, valid
