### ISSUE TITLE
Client doesn't take the time to close connection properly on window close

### ISSUE THREAD

**Issue by jmbarzee** [thyer/CS340winter2016#407] opened 2016-03-03 07:02 UTC
1) play a game
2) close client
3) notice errors server side from forcible connection close

**Comment by mcrowder65** [comment] 2016-03-03 14:11
Marked invalid because this has nothing to do with anything... And this probably happens when you close any client connected to a server

**Comment by thyer** [comment] 2016-03-03 16:32
Closing this bug unless tester can give expected behavior from specifications

**Closed by thyer** 2016-03-03 16:32 UTC
Labels: invalid, P4: Incorrect behavior that doesn't affect gameplay, Phase 2, Team 13
