### ISSUE TITLE
Maritime 4 of anything: 1 wheat => doesn't give me a wheat.

### ISSUE THREAD

**Issue by CaptBoscho** [thyer/CS340winter2016#64] opened 2016-03-01 23:35 UTC

**Comment by DanielSaunders** [comment] 2016-03-02 04:10
Cannot reproduce. I could trade 4 brick for 1 wheat. I could also trade 4 wheat for a wood. Does not seem to be a problem. Perhaps it has been fixed inadvertently?

**Closed by DanielSaunders** 2016-03-02 04:10 UTC
Labels: P3: Incorrect behavior that affects gameplay, Phase 2, Team 3

**Comment by CaptBoscho** [comment] 2016-03-02 15:14
I was trading 4 wood for 1 wheat and I wasn't getting the wheat back. I'll verify

**Comment by CaptBoscho** [comment] 2016-03-02 15:31
You're right, I'm sorry haha
