### ISSUE TITLE
Points Updating

### ISSUE THREAD

**Issue by KasiKarra** [thyer/CS340winter2016#683] opened 2016-03-26 05:44 UTC
Yes I couldn't reproduce it, but I am going to mention it anyways.

Placed a settlement and haven’t finished my turn yet.  Points on turntracker update, but the points controller does not.  Mark played a settlement last when it didn’t update the points controller, but Sam placed a City and the points bar updated the first city, but not the second city

![p3thing](https://cloud.githubusercontent.com/assets/16614325/14058367/62372b82-f2e3-11e5-965d-204951e8c374.png)
![p3thingie](https://cloud.githubusercontent.com/assets/16614325/14058371/776dbbce-f2e3-11e5-9ffe-895d8e16bc26.png)

**Comment by thyer** [comment] 2016-03-28 16:45
Let's try and get this duped - if both teams can't reproduce, we'll close it. But otherwise, this seems like an interesting bug.

**Comment by cmriboldi** [comment] 2016-03-30 03:23
I figured out what this bug really is. I don't think that it should be considered one of our bugs because it's a bug with the view. The problem isn't that it's not showing the correct number of points. If you look closely it is displaying the correct number of points. The problem is that it has added an extra empty dot at the end. There are 11 dots not 10. And the numbers really do match. We have no control over how the view functions so I don't think it should be considered as our bug.

**Comment by thyer** [comment] 2016-03-30 18:41
What on earth?? How did the 11th dot get there? I just opened the demo client and our old client and both only had 10.

**Closed** 2016-03-30 23:06 UTC
Labels: invalid, Phase 3, Team 1
