### ISSUE TITLE
Team 4: Robbing Waiting Dialog Doesn't Close

### ISSUE THREAD

**Issue by wesleyackerman** [thyer/CS340winter2016#238] opened 2016-03-03 02:14 UTC
A seven was rolled by a player. Robbing proceeded correctly. The next player also rolled a seven. (I realize that may be hard to replicate, but I figured I would include it just in case that was a factor). Only the player who rolled a seven and one other player had to discard some resources. Once both players had discarded the necessary resources, the waiting dialog didn't go away on the player who rolled the seven. The other players' views were fine, but the player who rolled the seven was unable to end their turn.

**Comment by eaglewyng** [comment] 2016-03-03 02:21
Hmmm that's interesting, thanks for the info. The only thing I can think of is perhaps there's a race condition that causes the state to not be updated correctly. Did you try closing the client and rejoining the game? If so, did gameplay resume as usual?

**Comment by wesleyackerman** [comment] 2016-03-03 02:22
Yes, I closed and signed in again, and I was able to move the robber and continue the game as normal.

**Comment by eaglewyng** [comment] 2016-03-03 02:23
OK, thanks! I think we just need to be sure and force an update of the game as soon as a player is done discarding.

**Comment by thyer** [comment] 2016-03-04 02:28
@eaglewyng if this is really verified as a race condition, let me know and I'll knock it down to a P4.

**Comment by matthewfcarlson** [comment] 2016-03-07 21:28
We implemented some fixes that we thought might cause it to occur. We think it might have been caused by an update from the poller happening at the same time as a update from discarding. We haven't been able to reproduce the bug since the fix was implemented.

**Comment by eaglewyng** [comment] 2016-03-07 22:44
I think it was a concurrency issue or a race condition. @matthewfcarlson implemented some fixes that seem to have resolved this because we haven't seen this for days.

**Closed** 2016-03-30 16:50 UTC
Labels: fixed, P4: Incorrect behavior that doesn't affect gameplay, Phase 2, TA-Fixed, Team 4
