### ISSUE TITLE
Placing initial road

### ISSUE THREAD

**Issue by ScottVaughan** [thyer/CS340winter2016#313] opened 2016-03-03 04:01 UTC
Upon “placing” a players first road, the road does not appear on the view nor on any other players Gui's. This doesn't allow the game to progress.

**Comment by dbitter2** [comment] 2016-03-06 23:28
fixed

**Comment by Sicilica** [comment] 2016-03-07 05:24
Duplicate of issue #436

**Closed** 2016-03-07 21:41 UTC
Labels: duplicate, fixed, P3: Incorrect behavior that affects gameplay, Phase 2, Team 12
