### ISSUE TITLE
Development Card View is not updating the display count for cards after playing them

### ISSUE THREAD

**Issue by danielmhair** [thyer/CS340winter2016#383] opened 2016-03-03 06:23 UTC
I played 2 victory point cards in one turn. The first card I used, I checked my victory point cards remaining and it decremented from 2 to 1 correctly. I used another card and then viewed my victory point cards again and my number of victory point cards should have been 0. It displayed 1. However, the card was disabled when I had no more (although it said I had one more).

This happened to another development card as well.

**Comment by calebtonkinson** [comment] 2016-03-07 16:03
Duplicate of 284

**Closed** 2016-03-30 16:50 UTC
Labels: duplicate, fixed, P4: Incorrect behavior that doesn't affect gameplay, Phase 2, Team 16
