### ISSUE TITLE
Round 2 Setup (Clayton)

### ISSUE THREAD

**Issue by kking937** [thyer/CS340winter2016#325] opened 2016-03-03 04:12 UTC
On a two client set up as first and second players, after placing my second round setup, the pull up map didn't disappear telling me to place a settlement.

**Comment by jakebrucebrewer** [comment] 2016-03-04 19:38
@kking937 is this reproducible?

**Comment by kking937** [comment] 2016-03-04 20:45
I haven't been able to reproduce it.

**Comment by thyer** [comment] 2016-03-04 22:34
Marking as invalid since tester can't provide steps for reproduction.

**Closed** 2016-03-04 22:40 UTC
Labels: invalid, Phase 2, Team 1
